name: Apply KBO Update

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - KBO-codes

jobs:
  apply-kbo-update:
    runs-on: ubuntu-latest
    environment: KBO
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: KBO-codes

      - name: Download from SFTP
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          pass: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          run: |
            sftp -P 22 ftp.DylanVanAssche@ftps.economie.fgov.be <<EOF
            get /home/ftp.DylanVanAssche/home/ftp.DylanVanAssche/KboOpenData_0311_2026_03_25_Update.zip /tmp/kbo-update.zip
            bye
            EOF

      - name: Run update script
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_UPDATE_PATH: ${{ secrets.FTP_UPDATE_PATH }}
          FTP_FULL_PATH: ${{ secrets.FTP_FULL_PATH }}
        run: |
          chmod +x scripts/apply-kbo-update.sh
          ./scripts/apply-kbo-update.sh
